// scripts/fixtures.js
// Datos de muestra para sembrar el corpus en LOCAL cuando no hay YOUTUBE_API_KEY.
// Permiten demostrar la app end-to-end (score, MMR, modos, guardados) sin gastar
// cuota ni exponer una API key. En produccion, seed.js usa la YouTube API real.

export const FIXTURE_CHANNELS = [
  { channel_id: "UC_growth", title: "Growth Systems", subscriber_count: 240000 },
  { channel_id: "UC_b2b", title: "B2B SaaS Lab", subscriber_count: 95000 },
  { channel_id: "UC_edu", title: "EduMarketing ES", subscriber_count: 52000 },
  { channel_id: "UC_copy", title: "Copywriting Deep", subscriber_count: 410000 },
  { channel_id: "UC_lead", title: "Leadership Frameworks", subscriber_count: 1300000 },
  { channel_id: "UC_prod", title: "Productividad Real", subscriber_count: 78000 },
  { channel_id: "UC_viral", title: "Viral Hacks Daily", subscriber_count: 3200000 },
  { channel_id: "UC_neg", title: "Negotiation Masters", subscriber_count: 180000 },
];

function mk(o) {
  return {
    description: "",
    has_captions: 1,
    has_chapters: 0,
    discovered_layer: 1,
    ...o,
    thumbnail_url: `https://i.ytimg.com/vi/${o.video_id}/mqdefault.jpg`,
    url: `https://www.youtube.com/watch?v=${o.video_id}`,
  };
}

export const FIXTURE_VIDEOS = [
  mk({
    video_id: "gem_lead_01",
    title: "Sistema completo de generacion de leads B2B (framework paso a paso)",
    channel_id: "UC_growth",
    channel_title: "Growth Systems",
    description:
      "Masterclass: framework y proceso de generacion de leads para SaaS B2B. Caso de estudio real.\n0:00 Intro\n2:15 El sistema\n10:40 Caso de estudio\n28:00 Plantillas",
    published_at: "2025-11-02T10:00:00Z",
    duration_seconds: 1980,
    view_count: 142000,
    like_count: 8900,
    comment_count: 640,
    has_chapters: 1,
    discovered_query: "generacion de leads",
  }),
  mk({
    video_id: "gem_b2b_02",
    title: "Estrategia de ventas B2B SaaS: deep dive en el embudo",
    channel_id: "UC_b2b",
    channel_title: "B2B SaaS Lab",
    description:
      "Deep dive: estrategia y sistema de ventas B2B SaaS. Webinar grabado.\n0:00 Contexto\n5:00 Embudo\n22:00 Cierre",
    published_at: "2025-10-18T09:00:00Z",
    duration_seconds: 2460,
    view_count: 58000,
    like_count: 4100,
    comment_count: 380,
    has_chapters: 1,
    discovered_query: "ventas B2B SaaS",
  }),
  mk({
    video_id: "gem_crm_03",
    title: "CRM para escuelas: como aumentar la conversion de inscripciones",
    channel_id: "UC_edu",
    channel_title: "EduMarketing ES",
    description:
      "Guia practica de CRM para escuelas y conversion de inscripciones. Proceso y plantillas.",
    published_at: "2025-09-30T12:00:00Z",
    duration_seconds: 1320,
    view_count: 21000,
    like_count: 1600,
    comment_count: 140,
    discovered_query: "CRM para escuelas",
  }),
  mk({
    video_id: "gem_copy_04",
    title: "Copywriting que convierte: framework de persuasion (masterclass)",
    channel_id: "UC_copy",
    channel_title: "Copywriting Deep",
    description:
      "Masterclass de copywriting. Framework de persuasion y estrategia.\n0:00 Intro\n3:30 Estructura\n18:00 Ejemplos\n35:00 Cierre",
    published_at: "2025-11-20T08:00:00Z",
    duration_seconds: 2700,
    view_count: 305000,
    like_count: 21000,
    comment_count: 1500,
    has_chapters: 1,
    discovered_query: "copywriting",
  }),
  mk({
    video_id: "gem_lead_05",
    title: "Liderazgo: sistema de negociacion para equipos de alto rendimiento",
    channel_id: "UC_lead",
    channel_title: "Leadership Frameworks",
    description:
      "Sistema y proceso de liderazgo y negociacion. Caso de estudio de un equipo real.",
    published_at: "2025-08-12T11:00:00Z",
    duration_seconds: 3100,
    view_count: 880000,
    like_count: 39000,
    comment_count: 2100,
    discovered_query: "liderazgo",
  }),
  mk({
    video_id: "gem_prod_06",
    title: "Productividad real: el proceso que uso para sistemas personales",
    channel_id: "UC_prod",
    channel_title: "Productividad Real",
    description:
      "Guia de productividad y desarrollo personal. Sistema y proceso editable.\n0:00 Intro\n4:00 El sistema\n16:00 Herramientas",
    published_at: "2025-12-01T07:00:00Z",
    duration_seconds: 1140,
    view_count: 33000,
    like_count: 2900,
    comment_count: 210,
    has_chapters: 1,
    discovered_query: "productividad",
  }),
  mk({
    video_id: "viral_clickbait_07",
    title: "ESTE TRUCO te hara MILLONARIO en 2025 (no clickbait)",
    channel_id: "UC_viral",
    channel_title: "Viral Hacks Daily",
    description: "Suscribete!!! El mejor truco. Link en la bio.",
    published_at: "2025-12-10T06:00:00Z",
    duration_seconds: 420,
    view_count: 2400000,
    like_count: 9000,
    comment_count: 300,
    has_captions: 0,
    discovered_query: "productividad",
  }),
  mk({
    video_id: "gem_neg_08",
    title: "Negociacion avanzada: framework de tacticas (deep dive)",
    channel_id: "UC_neg",
    channel_title: "Negotiation Masters",
    description:
      "Deep dive en negociacion. Framework, estrategia y proceso.\n0:00 Intro\n6:00 Tacticas\n24:00 Casos",
    published_at: "2025-07-22T10:00:00Z",
    duration_seconds: 2880,
    view_count: 126000,
    like_count: 9400,
    comment_count: 560,
    has_chapters: 1,
    discovered_query: "negociacion",
  }),
  mk({
    video_id: "gem_b2b_09",
    title: "Marketing educativo: estrategia de conversion de inscripciones",
    channel_id: "UC_edu",
    channel_title: "EduMarketing ES",
    description:
      "Estrategia de marketing educativo y conversion. Caso de estudio de una escuela.",
    published_at: "2025-10-05T09:30:00Z",
    duration_seconds: 1560,
    view_count: 18500,
    like_count: 1500,
    comment_count: 120,
    discovered_query: "marketing educativo",
  }),
  mk({
    video_id: "gem_growth_10",
    title: "Webinar: sistema de generacion de leads con automatizacion",
    channel_id: "UC_growth",
    channel_title: "Growth Systems",
    description:
      "Webinar completo. Sistema y proceso de generacion de leads automatizado.\n0:00 Intro\n8:00 Automatizacion\n30:00 Q&A",
    published_at: "2025-11-28T15:00:00Z",
    duration_seconds: 3500,
    view_count: 64000,
    like_count: 5200,
    comment_count: 410,
    has_chapters: 1,
    discovered_query: "generacion de leads",
  }),
  mk({
    video_id: "gem_copy_11",
    title: "Desarrollo personal: el framework de habitos que cambia todo",
    channel_id: "UC_copy",
    channel_title: "Copywriting Deep",
    description:
      "Guia de desarrollo personal. Framework y sistema de habitos.",
    published_at: "2025-09-14T08:00:00Z",
    duration_seconds: 900,
    view_count: 210000,
    like_count: 17000,
    comment_count: 980,
    discovered_query: "desarrollo personal",
  }),
  mk({
    video_id: "short_lowdur_12",
    title: "Tip rapido de ventas",
    channel_id: "UC_b2b",
    channel_title: "B2B SaaS Lab",
    description: "Un tip corto.",
    published_at: "2025-12-12T08:00:00Z",
    duration_seconds: 180,
    view_count: 9000,
    like_count: 300,
    comment_count: 10,
    has_captions: 0,
    discovered_query: "ventas B2B SaaS",
  }),
  mk({
    video_id: "gem_lead_13",
    title: "Estrategia B2B: proceso de prospeccion en frio que funciona",
    channel_id: "UC_lead",
    channel_title: "Leadership Frameworks",
    description:
      "Proceso y sistema de prospeccion B2B. Caso de estudio.\n0:00 Intro\n5:00 Proceso\n20:00 Resultados",
    published_at: "2025-06-30T10:00:00Z",
    duration_seconds: 1700,
    view_count: 95000,
    like_count: 7600,
    comment_count: 520,
    has_chapters: 1,
    discovered_query: "ventas B2B SaaS",
  }),
  mk({
    video_id: "gem_prod_14",
    title: "Productividad: guia de sistemas y frameworks (caso de estudio)",
    channel_id: "UC_prod",
    channel_title: "Productividad Real",
    description:
      "Guia profunda. Framework, sistema y proceso de productividad. Caso de estudio personal.",
    published_at: "2025-11-15T07:00:00Z",
    duration_seconds: 2200,
    view_count: 41000,
    like_count: 3600,
    comment_count: 280,
    discovered_query: "productividad",
  }),
  mk({
    video_id: "gem_neg_15",
    title: "Liderazgo y negociacion: masterclass de comunicacion",
    channel_id: "UC_neg",
    channel_title: "Negotiation Masters",
    description:
      "Masterclass. Estrategia de liderazgo y negociacion.\n0:00 Intro\n7:00 Comunicacion\n26:00 Practica",
    published_at: "2025-10-28T10:00:00Z",
    duration_seconds: 2600,
    view_count: 73000,
    like_count: 6100,
    comment_count: 350,
    has_chapters: 1,
    discovered_query: "negociacion",
  }),
  mk({
    video_id: "gem_growth_16",
    title: "Generacion de leads para SaaS: guia de copywriting de emails",
    channel_id: "UC_growth",
    channel_title: "Growth Systems",
    description:
      "Guia: copywriting de emails para generacion de leads SaaS. Proceso y plantillas.",
    published_at: "2025-12-05T09:00:00Z",
    duration_seconds: 1400,
    view_count: 52000,
    like_count: 4400,
    comment_count: 300,
    discovered_query: "copywriting",
  }),
];
